#!/bin/sh
# Display volume levels.

wpctl() {
    arg="$2"

    set -- "$1"
    if [ "$1" = set-volume ]; then
        set -- "$@" --limit=1.0
    fi

    set -- "$@" @DEFAULT_AUDIO_SINK@ "$arg"

    command wpctl "$@"
}

case "$BLOCK_BUTTON" in
    1) setsid --fork pavucontrol ;;
    2) wpctl set-mute toggle ;;
    4) wpctl set-volume 3%+ ;;
    5) wpctl set-volume 3%- ;;
    6) terminal -e "$EDITOR" "$0" ;;
esac

if wpctl get-volume | grep -q "[MUTED]"; then
    echo "^C1^  Muted^d^"
    exit
fi

volume_frac="$(wpctl get-volume | cut -d' ' -f2)"
volume="$(echo "$volume_frac * 100 / 1" | bc)"

if [ -z "$volume" ]; then
    exit 1
fi


if [[ ("$volume" -ge "0") ]] && [[ ("$volume" -le "24" ) ]]; then
	icon=" "
elif [[ ("$volume" -ge "26") ]] && [[ ("$volume" -le "49" ) ]]; then
	icon=" "
elif [[ ("$volume" -ge "50") ]] && [[ ("$volume" -le "74" ) ]]; then
	icon="󰕾 "
elif [[ ("$volume" -ge "75") ]] && [[ ("$volume" -le "100" ) ]]; then
	icon="  "
else
	icon="? "
fi

echo "^C2^$icon$volume%^d^"
